### ISSUE TITLE
Unexpected `evaluate` behavior with non-Float64 numbers

### ISSUE THREAD

**Issue by schillic** [JuliaIntervals/TaylorModels.jl#158]
Is it expected that `evaluate` gives vastly different results when using non-`Float64` numbers?

```julia
julia> using TaylorModels

julia> function eval(N)
    t = TaylorModels.Taylor1(3)
    q₁ = 1 + 2 * t + 2 * t^2
    I = interval(N(0), N(0))
    D = interval(N(-1), N(1))
    x0 = mid(D)
    TM = TaylorModels.TaylorModel1(q₁, I, x0, D)
    return evaluate(TM, domain(TM))
end;

julia> eval(Float64)
[-1, 5]

julia> eval(Float32)
[-3, 5]

julia> eval(Rational{Int})
[-3, 5]
```

**Comment by lbenet** [comment]
Thanks for reporting; that is indeed weird. I'll have a look, and I'll get back here.

Note that since lot is going on in IntervalArithmetic, and that has consequences in TaylorSeries, lots of changes will occur here...

**Comment by lbenet** [comment]
The problem seems to be in TaylorSeries:
```julia
julia> D32 = interval(-1f0, 1f0)
[-1f0, 1f0]

julia> D = interval(-1.0, 1.0)
[-1, 1]

julia> t = Taylor1(3)
 1.0 t + 𝒪(t⁴)

julia> q₁ =  1 + 2*t + 2*t^2
 1.0 + 2.0 t + 2.0 t² + 𝒪(t⁴)

julia> q₁(D)
[-1, 5]

julia> q₁(D32)
[-3, 5]

julia> evaluate(t^2, D)
[0, 1]

julia> evaluate(t^2, D32)
[-1, 1]
```

**Comment by lbenet** [comment]
> The problem seems to be in TaylorSeries:

Noup, the problem is in IntervalArithmetic v0.20.9: somehow, squaring doesn't work for `Interval{Float32}`
```julia
julia> D^2
[0, 1]

julia> D32^2
[-1f0, 1f0]

julia> @which D32^2
^(x::Number, p::Integer)
     @ Base intfuncs.jl:311
```
The problem is solved in current master of IntervalArithmetic.

**Comment by schillic** [comment]
Thanks for working this out! Then there is nothing we can do for now and this should eventually get resolved when the new version is supported.
I leave it to you to keep this issue open as a reminder or close it.

**Comment by Mark-L-Stone** [comment]
Is there an update on this issue?  

More broadly, are there still any known bugs when using TaylorModels.jl with BigFloat numbers, such as BigFloat128 or BigFloat256 ?

**Comment by schillic** [comment]
Indeed, the problem persists with the new package versions. I just updated the code to run in the latest version.

**Comment by schillic** [comment]
But the squaring works now, so the root cause is somewhere else...

**Comment by lbenet** [comment]
I'll try to have a look onto this. Somehow my time in TaylorModels has been in details of #188; sorry...

@Mark-L-Stone I haven't played too much with BigFloat's, and certainly not with BigFloat128 or BigFloat256. If you are at it, it would be great if you can suggest some tests, to uncover any bug.

**Comment by schillic** [comment]
~~I only tried `Float32` and got the same as in https://github.com/JuliaIntervals/TaylorModels.jl/issues/158#issuecomment-1911126221.~~

**Comment by schillic** [comment]
Sorry, completely wrong. The issue in https://github.com/JuliaIntervals/TaylorModels.jl/issues/158#issuecomment-1911126221 is fixed. But I still get the different results reported in the OP even for `Float32`.

**Comment by lbenet** [comment]
This is what I've got so far. The `t` inside the function, as it is, is actually a `Taylor1{Float64}`, and therefore `TM` is a `TaylorModel1{Float64, N}`, where `N` is the numeric type of the intervals. So, my guess is that everything seems consistent, but having different numeric types (for the coefficients and for the intervals) somehow widens up the results which are `Interval{Float64}`. 

A work around is to have the same numeric type for coefficients and intervals:
```julia
julia> function eval1(N)
    t = TaylorModels.Taylor1(N, 3)
    q₁ = 1 + 2 * t + 2 * t^2
    I = interval(N(0), N(0))
    D = interval(N(-1), N(1))
    x0 = mid(D)
    TM = TaylorModels.TaylorModel1(q₁, I, x0, D)
    @show(typeof(t), typeof(TM)(
    return TaylorModels.evaluate(TM, domain(TM))
end;

julia> eval1(Float64)
typeof(t) = Taylor1{Float64}
typeof(TM) = TaylorModel1{Float64, Float64}
[-1.0, 5.0]_com_NG

julia> eval1(Float32)
typeof(t) = Taylor1{Float32}
typeof(TM) = TaylorModel1{Float32, Float32}
[-1.0f0, 5.0f0]_com_NG

julia> eval1(Rational{Int})
typeof(t) = Taylor1{Rational{Int64}}
typeof(TM) = TaylorModel1{Rational{Int64}, Rational{Int64}}
[-1//1, 5//1]_com_NG
```

**Comment by lbenet** [comment]
Let me know what do you think on this.

**Comment by schillic** [comment]
Thanks! Indeed this fixes the issue.

It still is unexpected that this results in such a large gap. So maybe it is worth investigating why this happens.

I leave it to you whether you want to close this issue or keep it open to investigate further.
